name: Build (Ubuntu)

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/emscripten-build.yml'
      - '.github/workflows/macos-build.yml'
      - '.github/workflows/windows-build-msvc.yml'
      - '.github/workflows/windows-build-msys2.yml'

  pull_request:

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type: ["Release"]
        cmake_generator: ["Ninja"]
        shared_libs_enabled: ["ON"]

        config:
        - {
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            os: ubuntu-latest,
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          ninja-build \
          libsdl2-dev

    - name: Configure CMake
      run: >
        cmake
        -G ${{ matrix.cmake_generator }}
        -S ${{ github.workspace }}
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
        -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_SHARED_LIBS=${{ matrix.shared_libs_enabled }}

    - name: Build
      run: >
        cmake
        --build ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}
